version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    reviewers:
      - "EthanCoderPenguin2012"
    assignees:
      - "EthanCoderPenguin2012"